name: Build and Publish Extension [Container and Helm Chart - Multi-Arch]

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'charts/suse-ai-operator/**'
      - 'suse-ai-operator/**'
      - '.github/workflows/release-operator.yml'
    tags:
      - suse-ai-lifecycle-manager-*

env:
  CHART_PATH: charts/suse-ai-lifecycle-manager
  CHART_REGISTRY: oci://ghcr.io/leooamaral/chart
  IMAGE_NAME: ghcr.io/leooamaral/suse-ai-lifecycle-manager

jobs:
  prepare:
    outputs:
      VERSION: ${{ steps.tags.outputs.VERSION }}
      CHART_VERSION: ${{ steps.tags.outputs.CHART_VERSION }}
      PUBLISH: ${{ steps.tags.outputs.PUBLISH }}
      METADATA_TAGS: ${{ steps.tags.outputs.METADATA_TAGS }}
      NOTES_START_TAG: ${{ steps.tags.outputs.NOTES_START_TAG }}
    runs-on: ubuntu-latest
    steps:
      - name: Calculate tags
        id: tags
        shell: bash
        run: |
          ref=${{ github.ref }}
          case "$ref" in
            refs/tags/suse-ai-lifecycle-manager-*)
              VERSION="${ref#refs/tags/suse-ai-lifecycle-manager-}"
              IMAGE_TAGS="$VERSION"
              CHART_VERSION="$VERSION"
              NOTES_START_TAG=""

              {
                echo "METADATA_TAGS<<EOF"
                echo "$VERSION"
                if [[ "$VERSION" != *"-"* ]]; then
                  echo "latest"
                fi
                echo "EOF"
              } >> "$GITHUB_OUTPUT"

              PUBLISH=true
              ;;
            *)
              VERSION="${{ github.sha }}"
              IMAGE_TAGS="$VERSION"
              CHART_VERSION="$VERSION"
              NOTES_START_TAG=""

              {
                echo "METADATA_TAGS<<EOF"
                echo "$VERSION"
                echo "EOF"
              } >> "$GITHUB_OUTPUT"

              PUBLISH=false
              ;;
          esac

          echo "VERSION=$VERSION" >> "$GITHUB_OUTPUT"
          echo "IMAGE_TAGS=$IMAGE_TAGS" >> "$GITHUB_OUTPUT"
          echo "PUBLISH=$PUBLISH" >> "$GITHUB_OUTPUT"
          echo "CHART_VERSION=$CHART_VERSION" >> "$GITHUB_OUTPUT"
          echo "NOTES_START_TAG=$NOTES_START_TAG" >> "$GITHUB_OUTPUT"

  build:
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
        include:
          - arch: amd64
            runner: ubuntu-24.04
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    name: Build Container Image
    needs: prepare
    if: needs.prepare.outputs.PUBLISH == 'true'
    env:
      RELEASE_TAG: ${{ needs.prepare.outputs.METADATA_TAGS }}
    permissions:
      contents: read
      packages: write
    steps:  
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Nodejs with yarn caching
        uses: actions/setup-node@v5
        with:
          node-version: '20'
          cache: yarn

      - name: Enable Corepack
        run: corepack enable

      - name: Install dependencies
        run: yarn

      - name: Parse Extension Name
        env:
          GH_TOKEN: ${{ github.token }}
          TAG: "suse-ai-lifecycle-manager-${{ needs.prepare.outputs.VERSION }}"
        run: |          
          yarn parse-tag-name $TAG ${{ github.run_id }} "catalog"

      - name: Build image
        env:
          TAG: "suse-ai-lifecycle-manager-${{ needs.prepare.outputs.VERSION }}"
        run: |
          yarn publish-pkgs -c -i '' -r ghcr.io -o 'leooamaral' -t "$TAG"

      - name: Tag and Push Image
        env:
          VERSION: ${{ needs.prepare.outputs.VERSION }}
        run: |
          docker tag $IMAGE_NAME:$VERSION $IMAGE_NAME:$VERSION-${{ matrix.arch }}
          docker push $IMAGE_NAME:$VERSION-${{ matrix.arch }}

  manifest:
    name: Create Container Manifest and Helm Chart
    needs: [prepare, build]
    env:
      RELEASE_TAG: ${{ needs.prepare.outputs.METADATA_TAGS }}
    runs-on: ubuntu-latest
    if: needs.prepare.outputs.PUBLISH == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
    
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create multi-arch manifest
        env:
          VERSION: "${{ needs.prepare.outputs.VERSION }}"
        run: |
          while IFS= read -r tag; do
            echo "Creating manifest for tag: $tag"
          
            docker buildx imagetools create \
              -t $IMAGE_NAME:$tag \
              $IMAGE_NAME:$VERSION-amd64 \
              $IMAGE_NAME:$VERSION-arm64
          
          done <<< "${RELEASE_TAG}"

      - name: Package Helm Chart
        id: package
        run: |
          chart_package=$(helm package $CHART_PATH --destination . | awk '{print $NF}')
          echo "chart_package=$chart_package" >> $GITHUB_OUTPUT

      - name: Publish Helm Chart
        run: |
          helm push ${{ steps.package.outputs.chart_package }} \
            $CHART_REGISTRY
